### ISSUE TITLE
Error: ENOENT: no such file or directory, open leaflet-drift-marker/src/index.tsx

### ISSUE THREAD

**Issue by paveltretyakovru** [hugobarragon/react-leaflet-drift-marker#3]
Hi! When I trying to use this library I have seen the message. I think it's not normal. What can I do to fix this?

![image](https://user-images.githubusercontent.com/7935943/164732995-fab19133-ba9c-4ffd-9294-10ccf692e0f5.png)

**Comment by hugobarragon** [comment]
Hello, can you please create a repo on github so i cant try to replicate the issue, or create a codesandbox link
i need to see the your package json at least

**Comment by paveltretyakovru** [comment]
Aloha! :)
You don't need my repo. It's easy to reproduce the behavior.
```yarn add react-leaflet-drift-marker```

And that's all.  If you look to node_modules, you can see
![image](https://user-images.githubusercontent.com/7935943/207354349-90241f92-44dc-4a0b-89a1-e46370312096.png)

And of course webpack can't see **src/index.tsx** becouse the folder is not exists after installing the package.

![image](https://user-images.githubusercontent.com/7935943/207355400-a21b1d59-6e1e-45d6-a255-a3035e5dd48b.png)

**Comment by hugobarragon** [comment]
@paveltretyakovru I dont need your repo, I need a reproducible one for the error, it seems that it is your webpack configs or related to this issue with webpack
https://stackoverflow.com/questions/63195843/webpack-module-warning-failed-to-parse-source-map-from-data-url  

the src will never be included in a compiled package, this package is compile to the lib folder, so it will not have src folder, that its the source code and not es5 compliant code

react quick start  
https://create-react-app.dev/docs/getting-started#quick-start  
```
npx create-react-app my-app
cd my-app
npm start  

npm install react-leaflet-drift-marker
npm install
npm start

```   

![image](https://user-images.githubusercontent.com/35630927/207373080-05d39b50-56b2-4123-901a-b681df4b82b7.png)
