### ISSUE TITLE
Bump support up to react-leaflet@v4

### ISSUE THREAD

**Issue by stephenyeargin** [hugobarragon/react-leaflet-drift-marker#5]
I've loaded this package and it has worked fine with `react-leaflet`'s v4.0 release in [a project](https://github.com/transitnownash/wego-bus-map). I think the support constraint can be relaxed a bit.

https://github.com/hugobarragon/react-leaflet-drift-marker/blob/b78011d6ad06bc77595b9b57bd39ae7fe364db27/package.json#L53

**Comment by hugobarragon** [comment]
Hi, just changing that on package json will not work with react v4, its a major version and custom components may have changed, i will have to look into it, and if all apis are implemented, can you please create a code sandbox with reactv4 and this lib to check what seems to be the problem?

**Comment by stephenyeargin** [comment]
My solution, right or wrong, was to have the installer always use `--legacy-peer-deps` to get around it via an [`.npmrc` file](https://github.com/transitnownash/wego-bus-map/blob/main/.npmrc). You're right that my implementation doesn't use every feature of this library, so I can't say that it's fully compatible.

I'm using it at https://map.transitnownash.org/ (vehicles update every seven seconds) - [source](https://github.com/transitnownash/wego-bus-map) if you need to see it working.

**Comment by hugobarragon** [comment]
Great project, so happy its being used :)  

I will try to make a v4 to match react-leaflet

**Comment by hugobarragon** [comment]
https://github.com/hugobarragon/react-leaflet-drift-marker/pull/6
